export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const USER_ROUTE = '/user'
export const CATALOGUE_ROUTE = '/catalogue'
export const MAIN_ROUTE = '/'
